name: innerComposite
description: Set an output, then pass it to an Action that has a Post step.

runs:
  using: composite
  

  steps:
    - name: Set Value to 'foo'
      id: setter
      shell: bash
      run:
        echo "::set-output name=some-val::foo"
  
    - name: Assert value is 'foo'
      uses: ./isFoo
      with:
        value: '${{ steps.setter.outputs.some-val }}'
