name: Demo Nested Composites Break

on:
  workflow_dispatch:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: innerComposite
        uses: ./innerComposite

  nested-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: wrapperComposite
        uses: ./wrapperComposite
